name: Frontend CI/CD

on:
  push:
    branches:
      - feature/full-stack

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Client
          npm install

      - name: Run lint (optional check)
        run: |
          cd Client
          npm run lint || true

      - name: Build Vite app
        run: |
          cd Client
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync Client/dist s3://christopher-ogwudire-aws-lab-2026 --delete
